[package]
name = "iouring-echo-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iou = { git = "https:/github.com/twissel/iou", branch = "additional-methods"}
nix = "0.16.1"